config/routes.rb
Submiterr::Application.routes.draw do
  resources :applications
  root :to => 'applications#index'
  match 'applications/hide/:id' => 'applications#hide', :as => :hide_application
  match 'applications/approve/:id' => 'applications#approve', :as => :approve_application

end

app/models/application.rb
class Application < ActiveRecord::Base

   attr_accessible :attachment, :full_name, :linkedin, :country, :city, :job
   has_attached_file :attachment,
 		:url  => "/assets/products/:id/:style/:basename.:extension",
        :path => ":rails_root/public/uploads/:id/:style/:basename.:extension"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applications }
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application = Application.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/new
  # GET /applications/new.json
  def new
    job = nil
    @application = Application.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/1/edit
  def edit
    @application = Application.find(params[:id])
  end

  # POST /applications
  # POST /applications.json
  def create
    application = Application.new(params[:application])

    application.status = "waiting"
    if application.save
      redirect_to applications_path
    else
      render action: "new"
    end
  end

  # PUT /applications/1
  # PUT /applications/1.json
  def update
    @application = Application.find(params[:id])

    respond_to do |format|
      if @application.update_attributes(params[:application])
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end

  def hide
  @application = Application.find(params[:id])
    @application.status = "hide"
    @application.save
    redirect_to root_path
  end

  def approve
  @application = Application.find(params[:id])
    @application.status = "approved"
    @application.save
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_for @application do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 </br> <div class="form">
      <%= f.text_field :full_name, :placeholder => "jhon goldman" %></br></br>
      <%= f.select(:city, options_for_select([['tel aviv','tlv'], ['new york city','nyc']])) %>
     </br></br><span class="text-right">http://www.linkedin.com/</span><%= f.text_field :linkedin, :placeholder => "jhongoldman" %></br></br>
      <%= f.text_field :job, :placeholder => "job" %></br></br>
      <%= f.text_field :email, :placeholder => "example@example.com" %></br></br>
      pdf file :
     <%= f.file_field :attachment %>
  </div>

  <div class="actions">
    <%= f.submit :class => "submit-application" %>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<h2>Job Applications</h2>
<table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>Region & Country</th>
          <th>Job</th>
          <th>Time Created</th>
          <th>PDF file</th>
          <th>Linkedin</th>
          <th>Status</th>
          <th>Actions</th>
          </tr>
      </thead>
      <tbody>
  <% @applications.each do |application| %>
    <% if application.status != "hide" %>
       <tr>
          <td><%= application.full_name %></td>
          <td><%= "#{application.country if application.country}, #{application.city if application.city}" %></td>
          <td><%= application.job %></td>
          <td><%= time_ago_in_words(application.created_at) %></td>
          <td></td>
          <td><%= application.linkedin %></td>
          <td><%= application.status %></td>
          <td><div class="btn-group">
            <button class="btn">Actions</button>
            <button class="btn dropdown-toggle" data-toggle="dropdown">
              <span class="caret"></span>
             </button>
            <ul class="dropdown-menu">
                <li class="divider"></li>
                <li><%= link_to 'approve', approve_application_path(application) %></li>
     <!-- dropdown menu links begining -->
              <li><%= link_to 'delete', application_path(application),
            :confirm => 'Are you sure?', :method => :delete, :class => 'text-error' %><%= link_to 'hide', hide_application_path(application) %></li>
     <!-- dropdown menu links end -->
               </ul>
          </div></td> 
        </tr>
        <% end %>
    <% end %>
      </tbody>
    </table>

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Submiterr</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container" style="padding-top: 30px;">
		<%= yield %>
	</div>
	

</body>
</html>